-- v30: Add embedding column to kg_beliefs for B-4 recall integration.
--
-- Beliefs need a semantic vector so recall can match them against query
-- embeddings. We use a BLOB column (not a separate vec0 table) because
-- belief count is bounded — in-memory cosine over ~1k beliefs is sub-ms.
-- Existing facts use a separate vec0 table because there are 10x-100x
-- more of them; beliefs don't need that infrastructure.
--
-- NULL embedding = belief was created without an embedding client
-- available (or the client failed). Such beliefs are queryable by
-- exact lookup but won't surface in semantic recall.
--
-- Idempotent: the `ALTER TABLE ADD COLUMN` runs only when the column is
-- absent (guarded by `ensure_kg_beliefs_embedding_column` in
-- knowledge_schema.rs, mirroring the v29 PRAGMA pattern). Fresh
-- databases get the column via the inline CREATE TABLE in
-- knowledge_schema.rs.
