import { useEffect, useState } from "react";

type FileEntry = {
  path: string;
  kind: "root" | "shard";
  size: number;
  modifiedAt: string;
  autoGenerated: boolean;
};

type ApiList = { success: boolean; files?: FileEntry[]; error?: string };

export function CustomizationTab() {
  const [files, setFiles] = useState<FileEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const res = await fetch("/api/customization/files");
        const body = (await res.json()) as ApiList;
        if (!cancelled) {
          if (body.success && body.files) {
            setFiles(body.files);
          } else {
            setError(body.error ?? "Failed to load files");
          }
        }
      } catch (e) {
        if (!cancelled) setError(String(e));
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    void load();
    return () => {
      cancelled = true;
    };
  }, []);

  if (loading) return <div className="settings-card">Loading customization files…</div>;
  if (error) return <div className="settings-card error">{error}</div>;

  return (
    <section className="settings-card">
      <header>
        <h3>Customization</h3>
      </header>
      <p className="muted small">
        Edit the markdown files that shape your agent's behavior. Changes save back to{" "}
        <code>~/Documents/zbot/config/</code>.
      </p>
      <p className="muted small">{files.length} file(s) found.</p>
    </section>
  );
}
