import { useCallback, useEffect, useState } from "react";
import { FileEditor } from "./FileEditor";
import { FileList } from "./FileList";
import { useGlobalEvents } from "@/hooks/useGlobalEvents";
import type { GlobalEvent } from "@/services/transport/types";

type FileEntry = {
  path: string;
  kind: "root" | "shard";
  size: number;
  modifiedAt: string;
  autoGenerated: boolean;
};

type ApiList = { success: boolean; files?: FileEntry[]; error?: string };

export function CustomizationTab() {
  const [files, setFiles] = useState<FileEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedPath, setSelectedPath] = useState<string | null>(null);

  const loadFiles = useCallback(async () => {
    try {
      const res = await fetch("/api/customization/files");
      const body = (await res.json()) as ApiList;
      if (body.success && body.files) {
        setFiles(body.files);
        setError(null);
      } else {
        setError(body.error ?? "Failed to load files");
      }
    } catch (e) {
      setError(String(e));
    }
  }, []);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      await loadFiles();
      if (!cancelled) setLoading(false);
    })();
    return () => {
      cancelled = true;
    };
  }, [loadFiles]);

  // Refresh file list when the gateway broadcasts an external file change.
  // The editor's own 409-on-save flow handles edit conflicts; here we just
  // keep the list (and its mtimes) current.
  useGlobalEvents((event: GlobalEvent) => {
    if (event.type === "customization_file_changed") {
      void loadFiles();
    }
  });

  if (loading) return <div className="settings-card">Loading customization files…</div>;
  if (error) return <div className="settings-card error">{error}</div>;

  return (
    <section className="settings-card">
      <header>
        <h3>Customization</h3>
      </header>
      <p className="muted small">
        Edit the markdown files that shape your agent's behavior. Changes save back to{" "}
        <code>~/Documents/zbot/config/</code>.
      </p>
      <div style={{ display: "grid", gridTemplateColumns: "260px 1fr", gap: "var(--spacing-4)" }}>
        <FileList files={files} selectedPath={selectedPath} onSelect={setSelectedPath} />
        {selectedPath ? (
          <FileEditor key={selectedPath} path={selectedPath} />
        ) : (
          <div className="muted">Select a file to edit.</div>
        )}
      </div>
    </section>
  );
}
