import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render, screen, waitFor, act } from "@testing-library/react";

// ---------------------------------------------------------------------------
// Mock transport — capture onGlobalEvent callbacks so we can fire events at
// the registered handler from tests.
// ---------------------------------------------------------------------------

interface CapturedGlobalSub {
  callback: (e: { type: string; [k: string]: unknown }) => void;
  unsubscribe: ReturnType<typeof vi.fn>;
}

const globalSubs: CapturedGlobalSub[] = [];

const mockOnGlobalEvent = vi.fn(
  (callback: (e: { type: string }) => void) => {
    const unsubscribe = vi.fn();
    globalSubs.push({ callback, unsubscribe });
    return unsubscribe;
  },
);

vi.mock("@/services/transport", async () => {
  const actual = await vi.importActual<Record<string, unknown>>("@/services/transport");
  return {
    ...actual,
    getTransport: async () => ({
      onGlobalEvent: mockOnGlobalEvent,
    }),
  };
});

// Import after mock so the module captures the stub.
import { CustomizationTab } from "./CustomizationTab";

const initialFiles = [
  { path: "SOUL.md", kind: "root", size: 42, modifiedAt: "2026-05-02T12:00:00Z", autoGenerated: false },
];
const updatedFiles = [
  { path: "SOUL.md", kind: "root", size: 99, modifiedAt: "2026-05-02T13:00:00Z", autoGenerated: false },
  { path: "shards/new.md", kind: "shard", size: 10, modifiedAt: "2026-05-02T13:00:00Z", autoGenerated: false },
];

let fetchCallCount = 0;

beforeEach(() => {
  globalSubs.length = 0;
  mockOnGlobalEvent.mockClear();
  fetchCallCount = 0;

  globalThis.fetch = vi.fn(async (url: RequestInfo | URL) => {
    const u = url.toString();
    if (u.includes("/api/customization/files")) {
      fetchCallCount += 1;
      const files = fetchCallCount === 1 ? initialFiles : updatedFiles;
      return new Response(JSON.stringify({ success: true, files }), { status: 200 });
    }
    return new Response("not mocked", { status: 404 });
  }) as unknown as typeof fetch;
});

afterEach(() => {
  vi.clearAllMocks();
});

describe("CustomizationTab", () => {
  it("loads files on mount", async () => {
    render(<CustomizationTab />);
    await waitFor(() => {
      expect(screen.getByText("SOUL.md")).toBeInTheDocument();
    });
    expect(fetchCallCount).toBe(1);
  });

  it("subscribes to global events on mount", async () => {
    render(<CustomizationTab />);
    await waitFor(() => expect(globalSubs).toHaveLength(1));
  });

  it("refetches files when a customization_file_changed event fires", async () => {
    render(<CustomizationTab />);
    await waitFor(() => expect(globalSubs).toHaveLength(1));
    await waitFor(() => expect(fetchCallCount).toBe(1));

    act(() => {
      globalSubs[0].callback({
        type: "customization_file_changed",
        path: "shards/new.md",
        modified_at: "2026-05-02T13:00:00Z",
        timestamp: Date.now(),
      });
    });

    await waitFor(() => expect(fetchCallCount).toBe(2));
    await waitFor(() => {
      expect(screen.getByText("new.md")).toBeInTheDocument();
    });
  });

  it("ignores unrelated global events", async () => {
    render(<CustomizationTab />);
    await waitFor(() => expect(globalSubs).toHaveLength(1));
    await waitFor(() => expect(fetchCallCount).toBe(1));

    act(() => {
      globalSubs[0].callback({ type: "stats_update", timestamp: Date.now() });
    });

    // Give any pending microtasks a chance.
    await new Promise((r) => setTimeout(r, 10));
    expect(fetchCallCount).toBe(1);
  });
});
