import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { FileEditor } from "./FileEditor";

beforeEach(() => {
  globalThis.fetch = vi.fn(async (url: RequestInfo | URL, init?: RequestInit) => {
    const u = url.toString();
    if (u.includes("/api/customization/file?path=")) {
      return new Response(
        JSON.stringify({
          success: true,
          path: "SOUL.md",
          content: "soul body",
          version: "v1",
          autoGenerated: false,
        }),
        { status: 200 },
      );
    }
    if (u.endsWith("/api/customization/file") && init?.method === "PUT") {
      const body = JSON.parse(init.body as string);
      if (body.expectedVersion === "v1") {
        return new Response(
          JSON.stringify({ success: true, path: body.path, version: "v2" }),
          { status: 200 },
        );
      }
      return new Response(
        JSON.stringify({
          success: false,
          error: "version mismatch",
          currentContent: "external content",
          currentVersion: "v_external",
        }),
        { status: 409 },
      );
    }
    return new Response("not mocked", { status: 404 });
  }) as unknown as typeof fetch;
});

describe("FileEditor", () => {
  it("loads file content on mount", async () => {
    render(<FileEditor path="SOUL.md" />);
    await waitFor(() => {
      expect((screen.getByRole("textbox") as HTMLTextAreaElement).value).toBe("soul body");
    });
  });

  it("shows dirty badge when content changes", async () => {
    render(<FileEditor path="SOUL.md" />);
    await waitFor(() => screen.getByRole("textbox"));
    fireEvent.change(screen.getByRole("textbox"), { target: { value: "edited" } });
    expect(screen.getByText(/Modified/i)).toBeInTheDocument();
  });

  it("saves changes via PUT and clears dirty badge", async () => {
    render(<FileEditor path="SOUL.md" />);
    await waitFor(() => screen.getByRole("textbox"));
    fireEvent.change(screen.getByRole("textbox"), { target: { value: "edited" } });
    fireEvent.click(screen.getByRole("button", { name: /Save/i }));
    await waitFor(() => {
      expect(screen.queryByText(/Modified/i)).not.toBeInTheDocument();
    });
  });

  it("Discard reverts to disk content", async () => {
    render(<FileEditor path="SOUL.md" />);
    await waitFor(() => screen.getByRole("textbox"));
    fireEvent.change(screen.getByRole("textbox"), { target: { value: "edited" } });
    fireEvent.click(screen.getByRole("button", { name: /Discard/i }));
    expect((screen.getByRole("textbox") as HTMLTextAreaElement).value).toBe("soul body");
  });

  it("shows conflict banner when save returns 409", async () => {
    render(<FileEditor path="SOUL.md" />);
    await waitFor(() => screen.getByRole("textbox"));
    // Force a 409 by overriding fetch to always return 409 on PUT:
    globalThis.fetch = vi.fn(async (url: RequestInfo | URL, init?: RequestInit) => {
      const u = url.toString();
      if (u.endsWith("/api/customization/file") && init?.method === "PUT") {
        return new Response(
          JSON.stringify({
            success: false,
            error: "version mismatch",
            currentContent: "external content",
            currentVersion: "v_external",
          }),
          { status: 409 },
        );
      }
      return new Response("nope", { status: 404 });
    }) as unknown as typeof fetch;
    fireEvent.change(screen.getByRole("textbox"), { target: { value: "edited" } });
    fireEvent.click(screen.getByRole("button", { name: /Save/i }));
    await waitFor(() => {
      expect(screen.getByText(/changed on disk/i)).toBeInTheDocument();
    });
  });
});
