import { describe, it, expect, vi } from "vitest";
import { render, screen, fireEvent } from "@testing-library/react";
import { FileList } from "./FileList";

const sampleFiles = [
  { path: "SOUL.md", kind: "root" as const, size: 42, modifiedAt: "2026-05-02T12:00:00Z", autoGenerated: false },
  { path: "OS.md", kind: "root" as const, size: 1152, modifiedAt: "2026-05-02T12:00:00Z", autoGenerated: true },
  { path: "shards/memory_learning.md", kind: "shard" as const, size: 800, modifiedAt: "2026-05-02T12:00:00Z", autoGenerated: false },
];

describe("FileList", () => {
  it("renders root and shards sections", () => {
    render(<FileList files={sampleFiles} selectedPath={null} onSelect={() => {}} />);
    expect(screen.getByText("SOUL.md")).toBeInTheDocument();
    expect(screen.getByText("OS.md")).toBeInTheDocument();
    expect(screen.getByText("memory_learning.md")).toBeInTheDocument();
  });

  it("marks OS.md as auto-generated", () => {
    render(<FileList files={sampleFiles} selectedPath={null} onSelect={() => {}} />);
    expect(screen.getByText(/auto-regenerated on restart/i)).toBeInTheDocument();
  });

  it("invokes onSelect with the clicked path", () => {
    const onSelect = vi.fn();
    render(<FileList files={sampleFiles} selectedPath={null} onSelect={onSelect} />);
    fireEvent.click(screen.getByText("SOUL.md"));
    expect(onSelect).toHaveBeenCalledWith("SOUL.md");
  });

  it("highlights the selected file", () => {
    render(<FileList files={sampleFiles} selectedPath="SOUL.md" onSelect={() => {}} />);
    const row = screen.getByText("SOUL.md").closest("button");
    expect(row?.getAttribute("aria-selected")).toBe("true");
  });
});
