type FileEntry = {
  path: string;
  kind: "agent" | "prompt";
  size: number;
  modifiedAt: string;
  autoGenerated: boolean;
};

type Props = {
  files: FileEntry[];
  selectedPath: string | null;
  onSelect: (path: string) => void;
};

export function FileList({ files, selectedPath, onSelect }: Props) {
  const agent = files.filter((f) => f.kind === "agent");
  const prompts = files.filter((f) => f.kind === "prompt");

  const renderRow = (f: FileEntry) => {
    const displayName = f.kind === "prompt" ? f.path.replace(/^agent-prompts\//, "") : f.path.replace(/^agent\//, "");
    const isSelected = selectedPath === f.path;
    return (
      <button
        key={f.path}
        type="button"
        onClick={() => onSelect(f.path)}
        aria-pressed={isSelected}
        className={`btn btn--outline btn--sm${isSelected ? " btn--primary" : ""}`}
        style={{ display: "block", width: "100%", textAlign: "left", margin: "2px 0" }}
      >
        <div>
          <code>{displayName}</code>
          {f.autoGenerated && (
            <span className="muted small" style={{ marginLeft: "var(--spacing-2)" }}>
              (auto-regenerated on restart)
            </span>
          )}
        </div>
      </button>
    );
  };

  return (
    <div className="customization-file-list">
      {agent.length > 0 && (
        <>
          <h4 className="muted small" style={{ margin: "var(--spacing-2) 0" }}>
            Agent contracts
          </h4>
          {agent.map(renderRow)}
        </>
      )}
      {prompts.length > 0 && (
        <>
          <h4 className="muted small" style={{ margin: "var(--spacing-3) 0 var(--spacing-2)" }}>
            Agent prompts
          </h4>
          {prompts.map(renderRow)}
        </>
      )}
    </div>
  );
}
