type FileEntry = {
  path: string;
  kind: "root" | "shard";
  size: number;
  modifiedAt: string;
  autoGenerated: boolean;
};

type Props = {
  files: FileEntry[];
  selectedPath: string | null;
  onSelect: (path: string) => void;
};

export function FileList({ files, selectedPath, onSelect }: Props) {
  const root = files.filter((f) => f.kind === "root");
  const shards = files.filter((f) => f.kind === "shard");

  const renderRow = (f: FileEntry) => {
    const displayName = f.kind === "shard" ? f.path.replace(/^shards\//, "") : f.path;
    const isSelected = selectedPath === f.path;
    return (
      <button
        key={f.path}
        type="button"
        onClick={() => onSelect(f.path)}
        aria-selected={isSelected}
        className={`btn btn--outline btn--sm${isSelected ? " btn--primary" : ""}`}
        style={{ display: "block", width: "100%", textAlign: "left", margin: "2px 0" }}
      >
        <div>
          <code>{displayName}</code>
          {f.autoGenerated && (
            <span className="muted small" style={{ marginLeft: "var(--spacing-2)" }}>
              (auto-regenerated on restart)
            </span>
          )}
        </div>
      </button>
    );
  };

  return (
    <div className="customization-file-list">
      {root.length > 0 && (
        <>
          <h4 className="muted small" style={{ margin: "var(--spacing-2) 0" }}>
            Root
          </h4>
          {root.map(renderRow)}
        </>
      )}
      {shards.length > 0 && (
        <>
          <h4 className="muted small" style={{ margin: "var(--spacing-3) 0 var(--spacing-2)" }}>
            shards/
          </h4>
          {shards.map(renderRow)}
        </>
      )}
    </div>
  );
}
