// ============================================================================
// STATUS BAR
// Bottom status bar with AI content warning
// ============================================================================

import { AlertTriangle } from "lucide-react";

export function StatusBar() {
  return (
    <div className="flex items-center gap-2 px-4 py-2 bg-yellow-500/10 border-t border-yellow-500/20">
      <AlertTriangle className="size-4 text-yellow-500 shrink-0" />
      <p className="text-xs text-yellow-200">
        <strong>Warning:</strong> Content generated by AI may be inaccurate. Always verify important information.
      </p>
    </div>
  );
}
